module.exports = {
  "rules": {
    "array-bracket-spacing": [ 2, "always" ],
    "camelcase": [ 2, { "properties": "always" } ],
    "comma-spacing": [ 2, { "before": false, "after": true } ],
    "comma-style": [ 2, "last" ],
    "computed-property-spacing": [ 2, "never" ],
    "consistent-this": [ 2, "_this" ],
    "eol-last": 2,
    "func-names": 0,
    "func-style": 0,
    "indent": [ 2, 2 ],
    "key-spacing": 2,
    "linebreak-style": [ 2, "unix" ],
    "max-nested-callbacks": 0,
    "new-cap": 2,
    "new-parens": 2,
    "newline-after-var": [ 2, "always" ],
    "no-array-constructor": 2,
    "no-continue": 0,
    "no-inline-comments": 2,
    "no-lonely-if": 2,
    "no-mixed-spaces-and-tabs": 2,
    "no-multiple-empty-lines": 2,
    "no-nested-ternary": 2,
    "no-new-object": 2,
    "no-spaced-func": 2,
    "no-ternary": 0,
    "no-trailing-spaces": 2,
    "no-underscore-dangle": 0,
    "no-unneeded-ternary": 2,
    "object-curly-spacing": [ 2, "always" ],
    "one-var": 0,
    "operator-assignment": [ 2, "always" ],
    "operator-linebreak": [ 2, "before" ],
    "padded-blocks": [ 2, "never" ],
    "quote-props": [ 2, "as-needed", { "keywords": false } ],
    "quotes": [ 2, "double", "avoid-escape" ],
    "semi-spacing": [ 2, { "before": false, "after": true } ],
    "semi": [ 2, "always" ],
    "sort-vars": 0,
    "space-after-keywords": [ 2, "always" ],
    "space-before-blocks": [ 2, "always" ],
    "space-before-function-paren": [ 2, "never" ],
    "space-in-parens": [ 2, "never" ],
    "space-infix-ops": [ 2, { "int32Hint": true } ],
    "space-return-throw-case": 2,
    "space-unary-ops": [ 2, { "words": true, "nonwords": false } ],
    "spaced-comment": 0,
    "wrap-regex": 0
  }
};
